name: Web Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Build Web
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        flutter config --enable-web
        flutter build web --dart-define=OPENAI_API_KEY=$OPENAI_API_KEY 